"use strict";

const mongoose = require("mongoose");
const { REQUEST_STATUS } = require("../config/constants");

const tankerAssignmentSchema = new mongoose.Schema(
  {
    tankerNumber: { type: String, required: true, trim: true },
    driverId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Driver",
      required: true,
    },
    driverName:   { type: String, trim: true, default: "" }, // snapshot
    driverMobile: { type: String, trim: true, default: "" }, // snapshot
    dateTime:     { type: Date, required: true },
  },
  { _id: false },
);

const handoverEntrySchema = new mongoose.Schema(
  {
    fromTankerNumber:  { type: String, trim: true },
    fromDriverId:      { type: mongoose.Schema.Types.ObjectId, ref: "Driver" },
    fromDriverName:    { type: String, trim: true },
    fromDriverMobile:  { type: String, trim: true },
    fromDateTime:      { type: Date },
    toTankerNumber:    { type: String, trim: true },
    toDriverId:        { type: mongoose.Schema.Types.ObjectId, ref: "Driver" },
    toDriverName:      { type: String, trim: true },
    toDriverMobile:    { type: String, trim: true },
    toDateTime:        { type: Date },
    reason:            { type: String, required: true, maxlength: 500 },
    handedOverAt:      { type: Date, default: Date.now },
    handedOverBy:      { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  },
  { _id: false },
);

const requestSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    // Snapshot of member details at time of request
    societyName:   { type: String, required: true, trim: true },
    address:       { type: String, required: true, trim: true },
    contactPerson: { type: String, required: true, trim: true },
    mobileNumber:  { type: String, required: true, trim: true },
    notes:         { type: String, trim: true, maxlength: 500, default: "" },

    status: {
      type: String,
      enum: Object.values(REQUEST_STATUS),
      default: REQUEST_STATUS.PENDING,
    },

    // FIFO queue position — auto-assigned, sequential
    queuePosition: { type: Number, required: true },

    // Current assignment — replaced on handover; history preserved below
    tankerAssignment: { type: tankerAssignmentSchema, default: null },

    assignedAt: { type: Date, default: null },
    assignedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    // Full audit trail of every re-assignment
    handoverHistory: { type: [handoverEntrySchema], default: [] },

    // One-way distance from filling station — snapshot from member profile at submission
    distanceInKm: { type: Number, default: null },

    // Source-destination assignment
    source:              { type: String, trim: true, default: "" },
    destination:         { type: String, trim: true, default: "" },
    kilometer:           { type: Number, default: null },
    roundTripKilometer:  { type: Number, default: null },

    completedAt:  { type: Date, default: null },
    cancelledAt:  { type: Date, default: null },
    cancelReason: { type: String, default: "" },

    // True for requests auto-generated by the demo-traffic scheduler (utils/demoTrafficScheduler.js).
    // Always visible/queryable so reports can include or exclude them as needed — never hidden.
    isDemo: { type: Boolean, default: false },
  },
  {
    timestamps: true,
    versionKey: false,
  },
);

// Compound indexes for queue queries
requestSchema.index({ status: 1, queuePosition: 1 });
requestSchema.index({ userId: 1, status: 1 });
requestSchema.index({ queuePosition: 1 });
requestSchema.index({ "tankerAssignment.tankerNumber": 1 });
requestSchema.index({ "tankerAssignment.driverId": 1 });
requestSchema.index({ isDemo: 1 });

module.exports = mongoose.model("Request", requestSchema);
